// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workify.Infrastructure.DBContext;

#nullable disable

namespace Workify.Infrastructure.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251026145506_ChangeMigration")]
    partial class ChangeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("RoleId");

                    b.ToTable("JobSeekerRole");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId")
                        .IsUnique();

                    b.ToTable("JobSeekerSettings");
                });

            modelBuilder.Entity("Workify.Core.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2e6a46f-5a57-4f49-9c70-32606183d80a"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bf0139d0-1960-47b6-9145-69fc1df7400e"),
                            RoleName = "JobSeeker"
                        },
                        new
                        {
                            Id = new Guid("0f702f2f-127f-44c3-9744-256734a3fd2a"),
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("Workify.Core.Entities.TokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerRoleEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeekerEntity", "JobSeeker")
                        .WithMany("JobSeekerRoles")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.RoleEntity", "Role")
                        .WithMany("JobSeekerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerSettingsEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeekerEntity", "JobSeeker")
                        .WithOne("JobSeekerSettings")
                        .HasForeignKey("Workify.Core.Entities.JobSeekerSettingsEntity", "JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.TokenEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeekerEntity", "JobSeeker")
                        .WithOne("Token")
                        .HasForeignKey("Workify.Core.Entities.TokenEntity", "JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerEntity", b =>
                {
                    b.Navigation("JobSeekerRoles");

                    b.Navigation("JobSeekerSettings")
                        .IsRequired();

                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Core.Entities.RoleEntity", b =>
                {
                    b.Navigation("JobSeekerRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
