// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workify.Infrastructure.DBContext;

#nullable disable

namespace Workify.Infrastructure.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251026174612_New2Migration")]
    partial class New2Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workify.Core.Entities.EmployerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId")
                        .IsUnique();

                    b.ToTable("JobSeekerSettings");
                });

            modelBuilder.Entity("Workify.Core.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5c80f88-86c4-4e2f-92de-10ad09b6435a"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("cfb4f096-a6da-4da3-9503-ba0a320f74d8"),
                            RoleName = "JobSeeker"
                        },
                        new
                        {
                            Id = new Guid("0bbfb741-f856-4a2a-9758-02b251d14267"),
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("Workify.Core.Entities.TokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Workify.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("JobSeekerRole");
                });

            modelBuilder.Entity("Workify.Core.Entities.EmployerEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.UserEntity", "User")
                        .WithOne("Employer")
                        .HasForeignKey("Workify.Core.Entities.EmployerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.UserEntity", "User")
                        .WithOne("JobSeeker")
                        .HasForeignKey("Workify.Core.Entities.JobSeekerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerSettingsEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeekerEntity", "JobSeeker")
                        .WithOne("JobSeekerSettings")
                        .HasForeignKey("Workify.Core.Entities.JobSeekerSettingsEntity", "JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.TokenEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.UserEntity", "User")
                        .WithOne("Token")
                        .HasForeignKey("Workify.Core.Entities.TokenEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.RoleEntity", "Role")
                        .WithMany("JobSeekerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeekerEntity", b =>
                {
                    b.Navigation("JobSeekerSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Core.Entities.RoleEntity", b =>
                {
                    b.Navigation("JobSeekerRoles");
                });

            modelBuilder.Entity("Workify.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("Employer");

                    b.Navigation("JobSeeker");

                    b.Navigation("Token")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
