// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workify.Infrastructure.DBContext;

#nullable disable

namespace Workify.Infrastructure.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251115195355_NewMigrationWithResumeAndCavacnies")]
    partial class NewMigrationWithResumeAndCavacnies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployerEntityResumeEntity", b =>
                {
                    b.Property<Guid>("LikedResumeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WhoLikesId")
                        .HasColumnType("uuid");

                    b.HasKey("LikedResumeId", "WhoLikesId");

                    b.HasIndex("WhoLikesId");

                    b.ToTable("EmployerLikedResume", (string)null);
                });

            modelBuilder.Entity("EmployerEntityResumeEntity1", b =>
                {
                    b.Property<Guid>("DislikedResumeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WhoDislikesId")
                        .HasColumnType("uuid");

                    b.HasKey("DislikedResumeId", "WhoDislikesId");

                    b.HasIndex("WhoDislikesId");

                    b.ToTable("EmployerDislikedResume", (string)null);
                });

            modelBuilder.Entity("JobSeekerEntityVacancyEntity", b =>
                {
                    b.Property<Guid>("LikedVacancyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WhoLikesId")
                        .HasColumnType("uuid");

                    b.HasKey("LikedVacancyId", "WhoLikesId");

                    b.HasIndex("WhoLikesId");

                    b.ToTable("JobSeekerLikedVacancies", (string)null);
                });

            modelBuilder.Entity("JobSeekerEntityVacancyEntity1", b =>
                {
                    b.Property<Guid>("DislikedVacancyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WhoDislikesId")
                        .HasColumnType("uuid");

                    b.HasKey("DislikedVacancyId", "WhoDislikesId");

                    b.HasIndex("WhoDislikesId");

                    b.ToTable("JobSeekerDislikedVacancies", (string)null);
                });

            modelBuilder.Entity("Workify.Core.Entities.Employer.EmployerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("Workify.Core.Entities.Employer.EmployerSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.ToTable("EmployerSettings");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeeker.JobSeekerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeeker.JobSeekerSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId")
                        .IsUnique();

                    b.ToTable("JobSeekerSettings");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.ResumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("Resume");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a550aef8-76cd-49d7-992d-44426687bb82"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6e268631-8fa9-4978-a551-65a476c14e1a"),
                            RoleName = "JobSeeker"
                        },
                        new
                        {
                            Id = new Guid("1e3a2ff0-a8cd-4bf1-b6d8-0de5d6afbe31"),
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.TokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.VacancyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("EmployerEntityResumeEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.Other.ResumeEntity", null)
                        .WithMany()
                        .HasForeignKey("LikedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.Employer.EmployerEntity", null)
                        .WithMany()
                        .HasForeignKey("WhoLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployerEntityResumeEntity1", b =>
                {
                    b.HasOne("Workify.Core.Entities.Other.ResumeEntity", null)
                        .WithMany()
                        .HasForeignKey("DislikedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.Employer.EmployerEntity", null)
                        .WithMany()
                        .HasForeignKey("WhoDislikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSeekerEntityVacancyEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.Other.VacancyEntity", null)
                        .WithMany()
                        .HasForeignKey("LikedVacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.JobSeeker.JobSeekerEntity", null)
                        .WithMany()
                        .HasForeignKey("WhoLikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSeekerEntityVacancyEntity1", b =>
                {
                    b.HasOne("Workify.Core.Entities.Other.VacancyEntity", null)
                        .WithMany()
                        .HasForeignKey("DislikedVacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.JobSeeker.JobSeekerEntity", null)
                        .WithMany()
                        .HasForeignKey("WhoDislikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Core.Entities.Employer.EmployerEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.User.UserEntity", "User")
                        .WithOne("Employer")
                        .HasForeignKey("Workify.Core.Entities.Employer.EmployerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.Employer.EmployerSettingsEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.Employer.EmployerEntity", "Employer")
                        .WithOne("EmployerSettings")
                        .HasForeignKey("Workify.Core.Entities.Employer.EmployerSettingsEntity", "EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeeker.JobSeekerEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.User.UserEntity", "User")
                        .WithOne("JobSeeker")
                        .HasForeignKey("Workify.Core.Entities.JobSeeker.JobSeekerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeeker.JobSeekerSettingsEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeeker.JobSeekerEntity", "JobSeeker")
                        .WithOne("JobSeekerSettings")
                        .HasForeignKey("Workify.Core.Entities.JobSeeker.JobSeekerSettingsEntity", "JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.ResumeEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.JobSeeker.JobSeekerEntity", "Author")
                        .WithOne("Resume")
                        .HasForeignKey("Workify.Core.Entities.Other.ResumeEntity", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.TokenEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.User.UserEntity", "User")
                        .WithOne("Token")
                        .HasForeignKey("Workify.Core.Entities.Other.TokenEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.VacancyEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.Employer.EmployerEntity", "Author")
                        .WithMany("Vacancies")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserRoleEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.Other.RoleEntity", "Role")
                        .WithMany("JobSeekerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Core.Entities.User.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserSettingsEntity", b =>
                {
                    b.HasOne("Workify.Core.Entities.User.UserEntity", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("Workify.Core.Entities.User.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workify.Core.Entities.Employer.EmployerEntity", b =>
                {
                    b.Navigation("EmployerSettings")
                        .IsRequired();

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Workify.Core.Entities.JobSeeker.JobSeekerEntity", b =>
                {
                    b.Navigation("JobSeekerSettings")
                        .IsRequired();

                    b.Navigation("Resume")
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Core.Entities.Other.RoleEntity", b =>
                {
                    b.Navigation("JobSeekerRoles");
                });

            modelBuilder.Entity("Workify.Core.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Employer");

                    b.Navigation("JobSeeker");

                    b.Navigation("Token")
                        .IsRequired();

                    b.Navigation("UserRoles");

                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
